<?php
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
/**
 * Seed the application's database.
 *
 * @return void
 */
    public function run()
    {
        $this->call(UsersTableSeeder::class);
        $this->call(PlansTableSeeder::class);
        $this->call(CommentsTableSeeder::class);
        $this->call(MarkersTableSeeder::class);
        $this->call(RequestsTableSeeder::class);
        $this->call(FollowsTableSeeder::class);
        $this->call(ParticipantsTableSeeder::class);
        $this->call(NotificationsTableSeeder::class);
    }
}
class UsersTableSeeder extends Seeder
{
/**
 * Seed the application's database.
 *
 * @return void
 */
    public function run()
    {
        DB::table('users')->insert([
            array(
                'username'      => 'TrongQT',
                'email'         => 'trongqtbkap@gmail.com',
                'password'      => Hash::make('1234'),
                'full_name'     => 'Trần Quang Trọng',
                'phone_number'  => '01653586444',
                'gender'        => '0',
                'avatar'        => 'image/avatar/trong.jpg',
                'date_of_birth' => date('1997-12-22'),
            ),
            array(
                'username'      => 'TruongNV',
                'email'         => 'truongnv@gmail.com',
                'password'      => Hash::make('1234'),
                'full_name'     => 'Nguyễn Văn Trường',
                'phone_number'  => '01653586555',
                'gender'        => '0',
                'avatar'        => 'image/avatar/truong.jpeg',
                'date_of_birth' => date('1997-08-10'),
            ),
            array(
                'username'      => 'TaiMT',
                'email'         => 'taimt@gmail.com',
                'password'      => Hash::make('1234'),
                'full_name'     => 'Mẫn Tiến Tài',
                'phone_number'  => '01653586666',
                'gender'        => '0',
                'avatar'        => 'image/avatar/tai.jpeg',
                'date_of_birth' => date('1996-03-07'),
            ),
            array(
                'username'      => 'DungThu',
                'email'         => 'dungt@gmail.com',
                'password'      => Hash::make('1234'),
                'full_name'     => 'Nguyễn Văn Dũng',
                'phone_number'  => '01653586666',
                'gender'        => '0',
                'avatar'        => 'image/avatar/dung.jpeg',
                'date_of_birth' => date('1996-03-07'),
            ),
        ]);
    }
}
class PlansTableSeeder extends Seeder
{
/**
 * Seed the application's database.
 *
 * @return void
 */
    public function run()
    {
        DB::table('plans')->insert([
            array(
                'id'          => 13,
                'user_id'     => 4,
                'name'        => "Mù căng chải",
                'cover_image' => "public/plans/mucangchai.jpeg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-12 18:50:00"),
            ),
            array(
                'id'          => 14,
                'user_id'     => 1,
                'name'        => "Chơi sông Đà",
                'cover_image' => "public/plans/songda.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-12 19:50:00"),
            ),
            array(
                'id'          => 15,
                'user_id'     => 2,
                'name'        => "Đi chơi Lạng Sơn",
                'cover_image' => "public/plans/langson.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),
            array(
                'id'          => 16,
                'user_id'     => 3,
                'name'        => "Du lịch chùa Trâm",
                'cover_image' => "public/plans/chuatram.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-10 02:50:00"),
            ),
            array(
                'id'          => 17,
                'user_id'     => 4,
                'name'        => "Chơi Sa Pa",
                'cover_image' => "public/plans/sapa.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),
            array(
                'id'          => 18,
                'user_id'     => 1,
                'name'        => "Dã ngoại tràng An",
                'cover_image' => "public/plans/trangan.jpg",
                'start_time'  => date("2018-08-13 01:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-12 08:50:00"),
            ),
            array(
                'id'          => 19,
                'user_id'     => 2,
                'name'        => "Tam đảo",
                'cover_image' => "public/plans/tamdao.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-10 12:20:00"),
            ),
            array(
                'id'          => 20,
                'user_id'     => 3,
                'name'        => "Đi Hạ Long",
                'cover_image' => "public/plans/halong.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),
            array(
                'id'          => 21,
                'user_id'     => 4,
                'name'        => "Đi vịnh Lăng cô",
                'cover_image' => "public/plans/langco.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),
            array(
                'id'          => 22,
                'user_id'     => 1,
                'name'        => "Đảo Phú Quốc",
                'cover_image' => "public/plans/phuquoc.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-11 12:50:00"),
            ),
            array(
                'id'          => 23,
                'user_id'     => 2,
                'name'        => "Đi chơi Lạng Sơn",
                'cover_image' => "public/plans/langson.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),
            array(
                'id'          => 24,
                'user_id'     => 3,
                'name'        => "Tam cốc bích động",
                'cover_image' => "public/plans/tamcoc.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-24 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),
            array(
                'id'          => 25,
                'user_id'     => 4,
                'name'        => "Trở về PHong Nha kẻ bàng",
                'cover_image' => "public/plans/phongnha.jpg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-09-24 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),
            array(
                'id'          => 26,
                'user_id'     => 1,
                'name'        => "Chuyến đi Móng cái",
                'cover_image' => "public/plans/mongcai.jpeg",
                'start_time'  => date("2018-08-13 18:50:00"),
                'end_time'    => date("2018-08-28 18:50:00"),
                'created_at'  => date("2018-08-13 12:50:00"),
            ),

        ]);
    }
}
class RequestsTableSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('requests')->insert([
            array(
                'user_id' => 1,
                'plan_id' => 13,
                'state'   => 0,
            ),
            array(
                'user_id' => 2,
                'plan_id' => 14,
                'state'   => 1,
            ),
            array(
                'user_id' => 3,
                'plan_id' => 15,
                'state'   => 0,
            ),
        ]);
    }
}
class FollowsTableSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('follows')->insert([
            array(
                'user_id' => 1,
                'plan_id' => 13,
            ),
            array(
                'user_id' => 2,
                'plan_id' => 14,
            ),
            array(
                'user_id' => 3,
                'plan_id' => 15,
            ),
        ]);
    }
}
class ParticipantsTableSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('participants')->insert([
            array(
                'user_id' => 1,
                'plan_id' => 23,
            ),
            array(
                'user_id' => 2,
                'plan_id' => 24,
            ),
            array(
                'user_id' => 3,
                'plan_id' => 25,
            ),
        ]);
    }
}
class MarkersTableSeeder extends Seeder
{
/**
 * Seed the application's database.
 *
 * @return void
 */
    public function run()
    {
        DB::table('markers')->insert([
            array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 21,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.0277644,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.83415979999995,
                'place_detail'  => "{\"formatted_address\":\"Hà Nội, Hoàn Kiếm, Hà Nội, Việt Nam\",\"name\":\"Hà Nội\"}",
                'place_id'      => "ChIJoRyG2ZurNTERqRfKcnt_iOc",
                'plan_id'       => 13,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Xe máy",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 22,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.1992298,
                'leave_time'    => "2018-08-15 18:51:00",
                'lng'           => 105.42321160000006,
                'place_detail'  => "{\"formatted_address\":\"Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Ba Vì\"}",
                'place_id'      => "ChIJNbd72ZmKNDERGPiCUi1L57s",
                'plan_id'       => 13,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-16 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 23,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 21.7670046,
                'leave_time'    => "2018-08-16 18:51:00",
                'lng'           => 104.14660460000005,
                'place_detail'  => "{\"formatted_address\":\"Mù Cang Chải, Yên Bái, Việt Nam\",\"name\":\"Mù Cang Chải\"}",
                'place_id'      => "ChIJ35HrcXzaMjERng84RfjJcBM",
                'plan_id'       => 13,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 24,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 14,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 25,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 19:08:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 14,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 26,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 14,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 27,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 15,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "Ăn chơi nhảy múa",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 28,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 22:00:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 15,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 29,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 15,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ),
            array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 30,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.0277644,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.83415979999995,
                'place_detail'  => "{\"formatted_address\":\"Hà Nội, Hoàn Kiếm, Hà Nội, Việt Nam\",\"name\":\"Hà Nội\"}",
                'place_id'      => "ChIJoRyG2ZurNTERqRfKcnt_iOc",
                'plan_id'       => 16,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Xe máy",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 31,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.1992298,
                'leave_time'    => "2018-08-15 18:51:00",
                'lng'           => 105.42321160000006,
                'place_detail'  => 
"{\"formatted_address\":\"Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Ba Vì\"}",
                'place_id'      => "ChIJNbd72ZmKNDERGPiCUi1L57s",
                'plan_id'       => 16,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-16 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 32,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 21.7670046,
                'leave_time'    => "2018-08-16 18:51:00",
                'lng'           => 104.14660460000005,
                'place_detail'  => "{\"formatted_address\":\"Mù Cang Chải, Yên Bái, Việt Nam\",\"name\":\"Mù Cang Chải\"}",
                'place_id'      => "ChIJ35HrcXzaMjERng84RfjJcBM",
                'plan_id'       => 16,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 33,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 17,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 34,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 19:08:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 17,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 35,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 17,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 36,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 18,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "Ăn chơi nhảy múa",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 37,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 22:00:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 18,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 38,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 19,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ),
            array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 39,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.0277644,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.83415979999995,
                'place_detail'  => "{\"formatted_address\":\"Hà Nội, Hoàn Kiếm, Hà Nội, Việt Nam\",\"name\":\"Hà Nội\"}",
                'place_id'      => "ChIJoRyG2ZurNTERqRfKcnt_iOc",
                'plan_id'       => 20,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Xe máy",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 40,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.1992298,
                'leave_time'    => "2018-08-15 18:51:00",
                'lng'           => 105.42321160000006,
                'place_detail'  => 
"{\"formatted_address\":\"Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Ba Vì\"}",
                'place_id'      => "ChIJNbd72ZmKNDERGPiCUi1L57s",
                'plan_id'       => 20,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-16 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 41,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 21.7670046,
                'leave_time'    => "2018-08-16 18:51:00",
                'lng'           => 104.14660460000005,
                'place_detail'  => "{\"formatted_address\":\"Mù Cang Chải, Yên Bái, Việt Nam\",\"name\":\"Mù Cang Chải\"}",
                'place_id'      => "ChIJ35HrcXzaMjERng84RfjJcBM",
                'plan_id'       => 20,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 42,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 21,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 43,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 19:08:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 21,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 44,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 21,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 45,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 22,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "Ăn chơi nhảy múa",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 46,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 22:00:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 22,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 47,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 22,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ),
            array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 48,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.0277644,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.83415979999995,
                'place_detail'  => "{\"formatted_address\":\"Hà Nội, Hoàn Kiếm, Hà Nội, Việt Nam\",\"name\":\"Hà Nội\"}",
                'place_id'      => "ChIJoRyG2ZurNTERqRfKcnt_iOc",
                'plan_id'       => 23,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Xe máy",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 49,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.1992298,
                'leave_time'    => "2018-08-15 18:51:00",
                'lng'           => 105.42321160000006,
                'place_detail'  => 
"{\"formatted_address\":\"Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Ba Vì\"}",
                'place_id'      => "ChIJNbd72ZmKNDERGPiCUi1L57s",
                'plan_id'       => 23,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-16 18:51:00",
                'has_link'      => 1,
                'has_waypoints' => 0,
                'id'            => 50,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 21.7670046,
                'leave_time'    => "2018-08-16 18:51:00",
                'lng'           => 104.14660460000005,
                'place_detail'  => "{\"formatted_address\":\"Mù Cang Chải, Yên Bái, Việt Nam\",\"name\":\"Mù Cang Chải\"}",
                'place_id'      => "ChIJ35HrcXzaMjERng84RfjJcBM",
                'plan_id'       => 23,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 51,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 24,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 52,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 19:08:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 24,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 53,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 24,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 54,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 25,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "Ăn chơi nhảy múa",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 55,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 22:00:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 25,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 56,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 25,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-13 18:50:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 57,
                'index_in_plan' => 0,
                'label'         => null,
                'lat'           => 21.474368917160188,
                'leave_time'    => "2018-08-13 18:50:00",
                'lng'           => 105.85536104112555,
                'place_detail'  => "{\"formatted_address\":\"Bách Quang, Tp . Sông Công, Thái Nguyên, Việt Nam\",\"name\":\"Bách Quang\"}",
                'place_id'      => "ChIJvbU5d74hNTERI_0ZQtJvPwU",
                'plan_id'       => 26,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "Ăn chơi nhảy múa",
                'arriver_time'  => "2018-08-15 19:08:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 58,
                'index_in_plan' => 1,
                'label'         => null,
                'lat'           => 21.07912714669611,
                'leave_time'    => "2018-08-15 22:00:00",
                'lng'           => 105.38740518065413,
                'place_detail'  => "{\"formatted_address\":\"Thiên Sơn Suối Ngà, Vân Hòa, Ba Vì, Hà Nội, Việt Nam\",\"name\":\"Thiên Sơn Suối Ngà\"}",
                'place_id'      => "ChIJu5Lckr5gNDERojhxioGwjLk",
                'plan_id'       => 26,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ), array(
                'activity'      => "",
                'arriver_time'  => "2018-08-21 18:51:00",
                'has_link'      => 0,
                'has_waypoints' => 0,
                'id'            => 59,
                'index_in_plan' => 2,
                'label'         => null,
                'lat'           => 20.801566586212267,
                'leave_time'    => "2018-08-21 18:51:00",
                'lng'           => 105.30700114718923,
                'place_detail'  => "{\"formatted_address\":\"Tp . Hòa Bình, Hòa Bình, Việt Nam\",\"name\":\"Thành phố Hòa Bình\"}",
                'place_id'      => "ChIJhaYWcz1rNDERKe8dHbMMKRM",
                'plan_id'       => 26,
                'route_index'   => 0,
                'travel_mode'   => "DRIVING",
                'vehicle'       => "Ô tô",
                'waypoints'     => null,
            ),
        ]);
    }
}

class NotificationsTableSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('notifications')->insert([
            array(
                'user_id' => 1,
                'content' => 'Bạn đã được tham gia vào kế hoạch',
            ),
            array(
                'user_id' => 1,
                'content' => 'một người bạn của bạn đã bình luận về kế hoạch của bạn',
            ),
            array(
                'user_id' => 1,
                'content' => 'một người bạn của bạn đang theo dõi kế hoạch của bạn',
            ),
            array(
                'user_id' => 1,
                'content' => 'một người bạn của bạn muốn tham gia kế hoạch của bạn',
            ),
            array(
                'user_id' => 2,
                'content' => 'Bạn đã được tham gia vào kế hoạch',
            ),
            array(
                'user_id' => 2,
                'content' => 'một người bạn của bạn đã bình luận về kế hoạch của bạn',
            ),
            array(
                'user_id' => 2,
                'content' => 'một người bạn của bạn đang theo dõi kế hoạch của bạn',
            ),
            array(
                'user_id' => 2,
                'content' => 'một người bạn của bạn muốn tham gia kế hoạch của bạn',
            ),
            array(
                'user_id' => 3,
                'content' => 'Bạn đã được tham gia vào kế hoạch',
            ),
            array(
                'user_id' => 3,
                'content' => 'một người bạn của bạn đã bình luận về kế hoạch của bạn',
            ),
            array(
                'user_id' => 3,
                'content' => 'một người bạn của bạn đang theo dõi kế hoạch của bạn',
            ),
            array(
                'user_id' => 3,
                'content' => 'một người bạn của bạn muốn tham gia kế hoạch của bạn',
            ),
        ]);
    }
}
class CommentsTableSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('comments')->insert([
            array(
                'user_id'      => 1,
                'plan_id'      => 3,
                'content'      => 'thời gian phượt bao lâu',
                'date_created' => date("2018-07-23 14:45:23"),
            ),
            array(
                'user_id'      => 2,
                'plan_id'      => 2,
                'content'      => 'thời gian phượt bao lâu',
                'date_created' => date("2018-07-21 14:30:23"),
            ),
            array(
                'user_id'      => 3,
                'plan_id'      => 1,
                'content'      => 'thời gian phượt bao lâu',
                'date_created' => date("2018-07-22 14:15:23"),
            ),
            array(
                'user_id'      => 3,
                'plan_id'      => 1,
                'content'      => 'thời gian phượt bao lâu',
                'date_created' => date("2018-07-22 14:15:23"),
            ),
        ]);
    }
}
